### ISSUE TITLE
[PATCH]  Fix ctypes.CDLL(...) exception in Cygwin

### ISSUE THREAD

**Issue by j3ffhubb** [vokimon/python-wavefile#14]
Hello David,

I was porting my project to Windows using Cygwin when I discovered this bug, here is the patch I used to fix it:

http://pastebin.com/Vx2XAMKw

I'll post here if I discover any other issues in Cygwin

**Comment by vokimon** [comment]
Quite fast to fix. Try it out, just in case. Thanks for the report and patch.
