### ISSUE TITLE
[PATCH] Mac OSX support

### ISSUE THREAD

**Issue by j3ffhubb** [vokimon/python-wavefile#15]
Hello David,

Here's a patch for Mac OSX support (tested on OSX Yosemite, using libsndfile from Homebrew):

http://pastebin.com/yC3vtXiM

I'll continue testing and let you know if I find any other issues.

**Comment by vokimon** [comment]
Because the alternative is not having any support, and it does not affect other platforms i'll apply it, but let us know whether you find any issues.

**Comment by vokimon** [comment]
applied
