### ISSUE TITLE
recording audio from mic?

### ISSUE THREAD

**Issue by ousia** [vokimon/python-wavefile#22]
@vokimon, many thanks for your work with this library.

Excuse my very basic question, but is it possible to record sound from microphone with `python-wavefile`?

**Comment by vokimon** [comment]
`python-wavefile` just deals with the file input/output, and not with audio devices input/output. In the examples we are using another library for that, PyAudio, but our example just does output, not input. I have not tried it but it should be quite similar.

**Comment by vokimon** [comment]
I just added an example on how to do that:
https://github.com/vokimon/python-wavefile/blob/master/examples/record.py

**Comment by ousia** [comment]
Many thanks for your new sample.

I wanted to record sound starting and stopping it with a keystroke (something similar to https://github.com/illuusio/linux-audio-example/blob/master/portaudio/libsndfile_port_rec.c, but without “taking the nap” 😀).

I think I might be able to translate it.
