### ISSUE TITLE
Exception: could not import libsndfile dll, make sure the dll 'libsndfile-1' is in the path

### ISSUE THREAD

**Issue by alpereira7** [vokimon/python-wavefile#28]
Hi,
my code is `from wavefile import WaveReader`
and my exception is `Exception: could not import libsndfile dll, make sure the dll 'libsndfile-1' is in the path`

My path is
`'C:\\Users\\Pereira',
 'C:\\Users\\Pereira\\Anaconda3\\python37.zip',
 'C:\\Users\\Pereira\\Anaconda3\\DLLs',
 'C:\\Users\\Pereira\\Anaconda3\\lib',
 'C:\\Users\\Pereira\\Anaconda3',
 '',
 'C:\\Users\\Pereira\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Pereira\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Pereira\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Pereira\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Pereira\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Pereira\\.ipython'`
and I placed `libsndfile-1.dll` in `C:\\Users\\Pereira\\Anaconda3\\DLLs` but it still doesn't work.
Did I miss something ?
Thanks.

**Comment by vokimon** [comment]
Sadly i cannot be helpful in Windows platforms. Not sure about how dll work in windows. libsndfile is not an standalone library itself, it depend on some other libraries. So maybe dll of the rest of the libraries should be in the path too (libogg, liboggvorbis, liboggvorbisenc, libflac). Just guessing.

**Comment by vokimon** [comment]
@alpereira7 did you try to place all the libraries in Path, and not just libsndfile-1?

**Comment by vokimon** [comment]
I didn't get reply on this, so i consider it solved. But if this goes up again, feel free to reopen it and provide this missing information. If someone using this platform could help him, it would be nice.
