### ISSUE TITLE
how to convert wav file to alaw or mulaw format?

### ISSUE THREAD

**Issue by pratikghule** [vokimon/python-wavefile#29]
how to convert wav file to alaw or mulaw format?

**Comment by vokimon** [comment]
I didn't test it but i figure that you can just take the [Processing example](https://github.com/vokimon/python-wavefile#processing-example), set the output format in the output writer adding a parameter `format=Format.WAV|Format.MULAW` to the constructor and then just remove the changes (do not apply the .8 factor and do not append `" II"` to the title.

Say:

```python
import sys
from wavefile import WaveReader, WaveWriter, Format

with WaveReader(sys.argv[1]) as r :
	with WaveWriter(
			'output.wav',
			channels=r.channels,
			samplerate=r.samplerate,
                        format=Format.WAV|Format.ULAW,
			) as w :
		w.metadata.title = r.metadata.title
		w.metadata.artist = r.metadata.artist

		for data in r.read_iter(size=512) :
			sys.stdout.write("."); sys.stdout.flush()
			w.write(data)
```
