### ISSUE TITLE
Error opening 'badfile.wav': File contains data in an unknown format.

### ISSUE THREAD

**Issue by yuuyins** [vokimon/python-wavefile#30]
# Happened

When trying to `pytest test/wavefile.py`, the test fails with errors

    Error opening 'badfile.wav': File contains data in an unknown format.

# Expected

Pass tests successfully.

# Reproduce

1.  [Install Nix](https://nixos.org/download.html)
2.  `git clone https://github.com/vokimon/python-wavefile.git`
3.  `git checkout a915ec275bf85602180c1fc95e6919b4d4120d99`
4.  `cd python-wavefile`
5.  Create file `shell.nix`
    
        let
          pkgs = import <nixpkgs> {};
        in with pkgs; with python3Packages; mkShell {
          nativeBuildInputs = [
            pytest
            setuptools
          ];
        
          propagatedBuildInputs = [
            pyaudio
            numpy
            libsndfile
          ];
        
          checkInputs = [
            pyaudio
            numpy
            libsndfile
          ];
        
          LD_LIBRARY_PATH = lib.makeLibraryPath [ pkgs.libsndfile ];
        }
6.  `nix-shell --pure shell.nix`
7.  `pytest test/wavefileTest.py`

# Backtrace

    [nix-shell:/mnt/pro/dev/python-wavefile]$ pytest test/wavefileTest.py
    ============================================================================ test session starts =============================================================================
    platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
    rootdir: /mnt/pro/dev/python-wavefile
    collected 45 items
    
    test/wavefileTest.py .................F...........................                                                                                                     [100%]
    
    ================================================================================== FAILURES ==================================================================================
    __________________________________________________________________ LibSndfileTest.test_reader_withWrongfile __________________________________________________________________
    
    self = <test.wavefileTest.LibSndfileTest testMethod=test_reader_withWrongfile>
    
        def test_reader_withWrongfile(self) :
        	self.writeFile("badfile.wav","Bad content")
        	try :
    >   		r = wavefile.WaveReader("badfile.wav")
    
    test/wavefileTest.py:103:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    self = <wavefile.wavefile.WaveReader object at 0x7fb66245f6d0>, filename = 'badfile.wav', samplerate = 0, channels = 0, format = 0
    
        def __init__(self,
                    filename,
                    samplerate = 0,
                    channels = 0,
                    format = 0,
                    ) :
    
            self._info = SF_INFO(
                    samplerate = samplerate,
                    channels = channels,
                    format = format
                )
            self._sndfile = _lib.sf_open(_fsencode(filename), OPEN_MODES.SFM_READ, self._info)
            if _lib.sf_error(self._sndfile) :
    >           raise IOError("Error opening '%s': %s"%(
                    filename, _sferrormessage(_lib.sf_error(self._sndfile))))
    E           OSError: Error opening 'badfile.wav': Format not recognised.
    
    wavefile/wavefile.py:246: OSError
    
    During handling of the above exception, another exception occurred:
    
    self = <test.wavefileTest.LibSndfileTest testMethod=test_reader_withWrongfile>
    
        def test_reader_withWrongfile(self) :
        	self.writeFile("badfile.wav","Bad content")
        	try :
        		r = wavefile.WaveReader("badfile.wav")
        		self.fail("Exception expected")
        	except IOError as e :
    >   		self.assertEqual( (
        			"Error opening 'badfile.wav': File contains data in an unknown format.",
        		), e.args)
    E     AssertionError: Tuples differ: ("Error opening 'badfile.wav': File contains data in an unknown format.",) != ("Error opening 'badfile.wav': Format not recognised.",)
    E
    E     First differing element 0:
    E     "Error opening 'badfile.wav': File contains data in an unknown format."
    E     "Error opening 'badfile.wav': Format not recognised."
    E
    E     - ("Error opening 'badfile.wav': File contains data in an unknown format.",)
    E     + ("Error opening 'badfile.wav': Format not recognised.",)
    
    test/wavefileTest.py:106: AssertionError
    ========================================================================== short test summary info ===========================================================================
    FAILED test/wavefileTest.py::LibSndfileTest::test_reader_withWrongfile - AssertionError: Tuples differ: ("Error opening 'badfile.wav': File contains data in an unknown for...
    ======================================================================== 1 failed, 44 passed in 0.73s ========================================================================

# System information

-   NixOS 21.11pre323695.9aeeb7574fb (Porcupine) Linux 5.10.73 x86<sub>64</sub> x
-   <https://github.com/vokimon/python-wavefile/commit/a915ec275bf85602180c1fc95e6919b4d4120d99>

**Comment by vokimon** [comment]
Fixed in commit 5373965d7e0312bb3c8c056df9504b0442648ab3. 

Libsndfile changed its messages. Tests now support both versions.

Thanks for reporting.
