### ISSUE TITLE
Wrong dllName for FreeBSD platform

### ISSUE THREAD

**Issue by mkernalcon** [vokimon/python-wavefile#32]
On FreeBSD 13.2-RELEASE, the value of sys.platform is 'freebsd13'. The correct dllName to pass to ctypes.CDLL on this platform should be 'libsndfile.so.1', like on the linux platform. Since FreeBSD is not in the list of known platforms, dllName defaults to 'libsndfile', which cannot be found.

My guess is a check for 'bsd' in sys.platform that sets dllName to the same value as for linux (wavefile/libsndfile.py line 21 or so) would suffice as a fix.

**Comment by vokimon** [comment]
Thanks a lot for the heads up. I was unaware that freebsd had a distinct sys.platform and a different dll naming for libsndfile.

As i am unable to test the platform. Could you provide a working pull request i could merge?

**Comment by vokimon** [comment]
I did a blind fix, but please, try it on the platform.
